# Schema for the configuration files of the Stark theme.

stark.settings:
  type: theme_settings
  label: 'Stark settings'

stark.breakpoints:
  type: theme_breakpoints_default
  label: 'Stark breakpoints'
